### ISSUE TITLE
[Feature Request] Additional Release as WinGet Package

### ISSUE THREAD

**Issue by AzureArmageddon** [KeyPuncher/WiinUPro#169]
I don't know about the technical/legal challenges involved (if any) in releasing for the [Windows Package Manager](https://github.com/microsoft/winget-cli) but it'd be rather convenient to be able to simply install with `winget install wiinupro` or `winget install wiinusoft`.

**Comment by jamesBrosnahan** [comment]
Hi Azure Armageddon,

Let's try filling out the YAML file that Microsoft requires submitting a winget package:
```yaml
PackageIdentifier:  # Publisher.package format.
PackageVersion:     # Version numbering format.
PackageLocale:      # BCP 47 format (e.g. en-US)
Publisher:          # The name of the publisher.
PackageName:        # The name of the application.
License:            # The license of the application.
ShortDescription:   # The description of the application.
Installers: 
 - Architecture:    # Enumeration of supported architectures.
   InstallerType:   # Enumeration of supported installer types (exe, msi, msix, inno, wix, nullsoft, appx).
   InstallerUrl:    # Path to download installation file.
   InstallerSha256: # SHA256 calculated from installer.
ManifestType:       # The manifest file type
ManifestVersion: 1.0.0
```
and this is Microsoft's example of complete YAML file:

```yaml
PackageIdentifier: Microsoft.WindowsTerminal
PackageVersion: 1.6.10571.0
PackageLocale: en-US
Publisher: Microsoft
PackageName: Windows Terminal
License: MIT
ShortDescription: The new Windows Terminal, a tabbed command line experience for Windows.
Installers: 
 - Architecture: x64
   InstallerType: msix
   InstallerUrl: https://github.com/microsoft/terminal/releases/download/v1.6.10571.0/Microsoft.WindowsTerminal_1.6.10571.0_8wekyb3d8bbwe.msixbundle
   InstallerSha256: 092aa89b1881e058d31b1a8d88f31bb298b5810afbba25c5cb341cfa4904d843
   SignatureSha256: e53f48473621390c8243ada6345826af7c713cf1f4bbbf0d030599d1e4c175ee
ManifestType: singleton
ManifestVersion: 1.0.0
```

```yaml
PackageIdentifier: KeyPuncher.WiinUPro  # Publisher.package format.
PackageVersion: 0.9.7 # Version numbering format.
PackageLocale: en-US      # BCP 47 format (e.g. en-US)
Publisher: KeyPuncher          # The name of the publisher.
PackageName: WiinUPro        # The name of the application.
License: Microsoft Public License (MS-PL)        # The license of the application.
ShortDescription: WiinUPro is a software tool that enables the use of Nintendo Wii and Wii U controllers as customizable input devices for PC games and applications.   # The description of the application.
Installers: 
 - Architecture: x64    # Enumeration of supported architectures.
   InstallerType: exe   # Enumeration of supported installer types (exe, msi, msix, inno, wix, nullsoft, appx).
   InstallerUrl: https://github.com/KeyPuncher/WiinUPro/releases/download/WiinUPro0.9.7b/WiinUPro_0.9.7_setup.exe    # Path to download installation file.
   InstallerSha256: 0E626B5D67B75840DD832AB88672D462701B3868F4B95D243CDD9B2806C3C2B4 # SHA256 calculated from installer.
ManifestType: singleton       # The manifest file type
ManifestVersion: 1.0.0
```
